name: Tests

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          # pip install -r requirements.txt
      - name: Install FFmpeg
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
